

--changeset author:create_table_shirt
CREATE TABLE IF NOT EXISTS Shirt (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(255) NOT NULL,
    brand VARCHAR(255) NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    sleeve_type VARCHAR(50) NOT NULL,  -- Для ENUM типа SleeveType
    size VARCHAR(50) NOT NULL,          -- Для ENUM типа Size
    material material_enum NOT NULL      -- Использование ENUM типа Material
    );