--liquibase formatted sql

--changeset author:create_material_enum
CREATE TYPE material_enum AS ENUM ('COTTON', 'LEATHER', 'POLYESTER', 'NYLON', 'DENIM', 'WOOL', 'FLEECE', 'SUEDE', 'LINEN', 'VINYL');


--changeset author:create_pants_table
CREATE TABLE IF NOT EXISTS Pants (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(255) NOT NULL,
    brand VARCHAR(255) NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    size VARCHAR(50) NOT NULL,
    material VARCHAR(50) NOT NULL
    );

