--liquibase formatted sql

--changeset Owl:init_script_DB_liquibase
--preconditions onFail:MARK_RAN
--precondition-sql-check expectedResult:0 SELECT count(*) FROM information_schema.tables WHERE table_name = 'jacket';
CREATE TABLE IF NOT EXISTS jacket (
                                      id SERIAL PRIMARY KEY,
                                      name VARCHAR(255) NOT NULL,
    size VARCHAR(50) NOT NULL,
    color VARCHAR(50),
    price NUMERIC(10, 2) NOT NULL,
    material VARCHAR(50) NOT NULL,
    hasHood BOOLEAN NOT NULL
    );

INSERT INTO jacket (name, size, color, price, material, hasHood) VALUES
                                                                     ('Light Jacket', 'M', 'Blue', 89.99, 'POLYESTER', false),
                                                                     ('Winter Jacket', 'L', 'Black', 129.99, 'COTTON', true),
                                                                     ('Leather Jacket', 'S', 'Brown', 343.00, 'LEATHER', false),
                                                                     ('Windbreaker', 'XL', 'Red', 59.99, 'NYLON', true),
                                                                     ('Denim Jacket', 'M', 'Dark Blue', 79.99, 'DENIM', false);

CREATE TABLE IF NOT EXISTS pants (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(255) NOT NULL,
    brand VARCHAR(255) NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    size VARCHAR(50) NOT NULL,
    material VARCHAR(50) NOT NULL
    );

INSERT INTO pants (name, brand, price, size, material) VALUES
                                                           ('Casual Pants', 'Brand A', 39.99, 'M', 'COTTON'),
                                                           ('Formal Pants', 'Brand B', 59.99, 'L', 'POLYESTER'),
                                                           ('Sport Pants', 'Brand C', 49.99, 'S', 'DENIM'),
                                                           ('Winter Pants', 'Brand D', 79.99, 'XL', 'COTTON'),
                                                           ('Chino Pants', 'Brand E', 45.00, 'M', 'COTTON');

CREATE TABLE IF NOT EXISTS shirt (
                                     id SERIAL PRIMARY KEY,
                                     name VARCHAR(255) NOT NULL,
    brand VARCHAR(255) NOT NULL,
    price NUMERIC(10, 2) NOT NULL,
    size VARCHAR(20) NOT NULL,
    material VARCHAR(255) NOT NULL,
    sleeve_type VARCHAR(100) NOT NULL
    );

INSERT INTO shirt (name, brand, price, sleeve_type, size, material) VALUES
                                                                        ('Casual Shirt', 'Brand A', 29.99, 'LONG', 'M', 'COTTON'),
                                                                        ('Formal Shirt', 'Brand B', 49.99, 'SHORT', 'L', 'POLYESTER'),
                                                                        ('T-Shirt', 'Brand C', 19.99, 'SLEEVELESS', 'S', 'NYLON'),
                                                                        ('Polo Shirt', 'Brand D', 35.00, 'SHORT', 'XL', 'DENIM'),
                                                                        ('Dress Shirt', 'Brand E', 59.99, 'LONG', 'M', 'WOOL');
CREATE TABLE IF NOT EXISTS role (
                                    id SERIAL PRIMARY KEY,
                                    name VARCHAR(255) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS "user" (
                                      id SERIAL PRIMARY KEY,
                                      username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

INSERT INTO "user" (username, password, email, created_at)
VALUES ('JohnDoe', 'securePassword', 'john.doe@example.com', CURRENT_TIMESTAMP);